---
sudo: required
sevices:
  - docker

language: python
python:
  - '2.7'

stages:
  - lint
  - test

env:
  - ANSIBLE_ROLES_PATH=$ANSIBLE_ROLES_PATH:$PWD/roles OPENSHIFT_VERSION=v3.9

install:
  - sudo apt-get update -qq
  - sudo apt-get install git jq

jobs:
  include:
  - stage: lint
    python: '2.7'
    script:
      - sudo apt-get install git
      - pip install --pre ansible apb yamllint
      - git clone https://github.com/ansible/ansible-kubernetes-modules.git $PWD/roles/ansible.kubernetes-modules
      - git clone https://github.com/ansibleplaybookbundle/ansible-asb-modules.git $PWD/roles/ansibleplaybookbundle.asb-modules
      # Verify all playbooks have valid syntax
      - |
        for PLAYBOOK in playbooks/{provision,deprovision,test}.yml
        do ansible-playbook $PLAYBOOK --syntax-check
        done
      # Verify apb.yml file is valid YAML
      - yamllint apb.yml

  - stage: test
    script:
      - chmod +x ${PWD}/apb-test.sh
      - ${PWD}/apb-test.sh
