---
# Modifications from https://github.com/ruromero/eclipse-che-apb/

- name: Create ServiceAccount
  k8s_v1_service_account:
    name: "che"
    namespace: "{{ namespace }}"
    state: present

- name: Create RoleBinding
  k8s_v1beta1_role_binding:
    name: "che-admin"
    namespace: "{{ namespace }}"
    state: present
    role_ref_name: admin
    role_ref_kind: ClusterRole
    subjects:
      - kind: ServiceAccount
        name: "che"
        namespace: "{{ namespace }}"

- name: Create Service
  k8s_v1_service:
    name: "che-host"
    namespace: "{{ namespace }}"
    state: present
    selector:
      app: "{{ application_name }}"
    ports:
      - name: http
        port: 8080
        target_port: 8080
      - name: debug
        port: 8000
        target_port: 8000
    labels:
      app: "{{ application_name }}"

- name: Create HTTPS Route
  openshift_v1_route:
    name: "{{ application_name }}"
    namespace: "{{ namespace }}"
    labels:
      app: "{{ application_name }}"
    tls_termination: edge
    tls_insecure_edge_termination_policy: Allow
    state: present
    spec_to_kind: Service
    spec_to_name: "che-host"
    spec_port_target_port: http
  register: route
  when: che_secure_routes

- name: Create HTTP Route
  openshift_v1_route:
    name: "{{ application_name }}"
    namespace: "{{ namespace }}"
    labels:
      app: "{{ application_name }}"
    state: present
    spec_to_kind: Service
    spec_to_name: "che-host"
    spec_port_target_port: http
  register: route
  when: not che_secure_routes

- name: Get server route
  openshift_v1_route:
    name: '{{ application_name }}'
    namespace: '{{ namespace }}'
  register: server_route_raw

- set_fact:
    route_host: "{{ server_route_raw.route.spec.host }}"

- name: Create Workspace PersistentVolumeClaim
  k8s_v1_persistent_volume_claim:
    name: "{{ application_name }}-workspace-claim"
    namespace: "{{ namespace }}"
    labels:
      app: "{{ application_name }}"
    state: present
    access_modes:
      - ReadWriteOnce
    resources_requests:
      storage: "{{ che_infra_kubernetes_pvc_quantity }}"
  when:
    - che_infra_kubernetes_pvc_strategy is defined
    - che_infra_kubernetes_pvc_strategy == "common"
