---
- name: "Create temporary keycloak directory"
  file:
    path: /tmp/keycloak
    state: directory

- include_role:
    name: keycloak-apb/provision-keycloak-apb
    tasks_from: deploy-keycloak.yml
  vars:
    application_name: keycloak
    admin_username:  "{{ che_keycloak_admin_username }}"
    admin_password: "{{ che_keycloak_admin_password }}"
    postgres_name: "postgres"

- include_role:
    name: keycloak-apb/set-keycloak-uri
  vars:
    application_name: keycloak
    admin_username:  "{{ che_keycloak_admin_username }}"
    admin_password: "{{ che_keycloak_admin_password }}"

- name: delete keycloak https route
  openshift_v1_route:
    name: 'keycloak'
    namespace: '{{ namespace }}'
    state: 'absent'

- name: Create keycloak http route
  openshift_v1_route:
    name: 'keycloak'
    namespace: '{{ namespace }}'
    labels:
      app: 'keycloak'
      service: 'keycloak'
    to_name: 'keycloak'
    to_kind: 'Service'
    spec_port_target_port: 'web'
  register: keycloak_route_raw

- name: Set keycloak uri from route
  set_fact:
    keycloak_uri: 'http://{{ keycloak_route_raw.route.spec.host }}'
