---
- name: Generate admin password
  set_fact:
    gen_password: "{{ lookup('password', '/tmp/keycloak/pass chars=ascii_letters,digits length=13') }}"

- name: Create Postgres secret
  k8s_v1_secret:
    name: '{{ postgres_name }}'
    namespace: '{{ namespace }}'
    labels:
      app: '{{ application_name }}'
    annotations:
      template.openshift.io/expose-username: "{.data['database-user']}"
      template.openshift.io/expose-password: "{.data['database-password']}"
      template.openshift.io/expose-database_name: "{.data['database-name']}"
    string_data:
      database-user: '{{ application_name }}'
      database-password: '{{ gen_password }}'
      database-name: '{{ database_name  | replace("-", "_") }}'

- name: Create Postgres service
  k8s_v1_service:
    name: '{{ postgres_name }}'
    namespace: '{{ namespace }}'
    labels:
      app: '{{ application_name }}'
    annotations:
      template.openshift.io/expose-uri: postgres://{.spec.clusterIP}:{.spec.ports[?(.name=="postgresql")].port}
    ports:
    - name: postgresql
      protocol: TCP
      port: 5432
      target_port: 5432
      node_port: 0
    selector:
      name: '{{ postgres_name }}'
    spec_type: ClusterIP
    session_affinity: None

- name: Create Persistent Volume Claim for Postgresql
  k8s_v1_persistent_volume_claim:
    name: '{{ postgres_name }}'
    namespace: '{{ namespace }}'
    labels:
      app: '{{ application_name }}'
    access_modes:
    - ReadWriteOnce
    resources_requests:
      storage: "{{ pvc_size }}"

- name: Create Postgresql DeploymentConfig
  openshift_v1_deployment_config:
    name: '{{ postgres_name }}'
    namespace: '{{ namespace }}'
    replicas: 1
    labels:
      app: '{{ application_name }}'
    spec_template_metadata_labels:
      app: '{{ application_name }}'
      name: '{{ postgres_name }}'
    selector:
      name: '{{ postgres_name }}'
    containers:
    - name: postgresql
      image: '{{ postgres_image }}:{{ postgres_image_tag }}'
      ports:
      - container_port: 5432
        protocol: TCP
      readiness_probe:
        timeout_seconds: 1
        initial_delay_seconds: 5
        exec:
          command:
          - "/bin/sh"
          - "-i"
          - "-c"
          - psql -h 127.0.0.1 -U $POSTGRESQL_USER -q -d $POSTGRESQL_DATABASE -c
            'SELECT 1'
      liveness_probe:
        timeout_seconds: 1
        initial_delay_seconds: 30
        tcp_socket:
          port: 5432
      env:
      - name: POSTGRESQL_USER
        value_from:
          secret_key_ref:
            name: '{{ postgres_name }}'
            key: database-user
      - name: POSTGRESQL_PASSWORD
        value_from:
          secret_key_ref:
            name: '{{ postgres_name }}'
            key: database-password
      - name: POSTGRESQL_DATABASE
        valueFrom:
          secret_key_ref:
            name: '{{ postgres_name }}'
            key: database-name
      resources:
        limits:
          memory: '512Mi'
      volume_mounts:
      - name: '{{ postgres_name }}-data'
        mount_path: "/var/lib/pgsql/data"
      termination_message_path: "/dev/termination-log"
    volumes:
    - name: '{{ postgres_name }}-data'
      persistent_volume_claim:
        claim_name: '{{ postgres_name }}'
