---
- name: Create keycloak service
  k8s_v1_service:
    name: '{{ application_name }}'
    namespace: '{{ namespace }}'
    labels:
      app: '{{ application_name }}'
      service: '{{ application_name }}'
    selector:
      app: '{{ application_name }}'
      service: '{{ application_name }}'
    ports:
    - name: web
      port: 80
      target_port: 8080

- name: Process DeploymentConfig from template
  template:
    src: keycloak-dc.yml.j2
    dest: "/tmp/keycloak/keycloak-dc.yml"
  register: dc

- name: Create DeploymentConfig
  openshift_v1_deployment_config:
    name: "{{ application_name }}"
    namespace: "{{ namespace}}"
    state: present
    src: "{{ dc.dest | default(dc.path) }}"
