---
- name: eclipse-che-apb playbook to provision the application
  hosts: localhost
  gather_facts: false
  connection: local
  vars:
    postgresql_admin_password: admin123
    postgresql_version: 9.6
    database_name: keycloak
  roles:
    - role: ansible.kubernetes-modules
      install_python_requirements: no
    - role: ansibleplaybookbundle.asb-modules
  tasks:
    - include_role:
        name: provision-eclipse-che-apb
