---
- name: eclipse-che-apb playbook to provision the application
  hosts: localhost
  gather_facts: false
  connection: local
  vars:
    postgresql_admin_password: admin123
    postgresql_version: 9.6
    database_name: keycloak
  roles:
  - role: ansible.kubernetes-modules
    install_python_requirements: no
  - role: ansibleplaybookbundle.asb-modules
  tasks:
    #  - include_role:
    #      name: ansible.kubernetes-modules
    #  - include_role:
    #      name: ansibleplaybookbundle.asb-modules
  - name: Generate admin password
    set_fact:
      gen_password: "{{ lookup('password', '/tmp/keycloak_pass chars=ascii_letters,digits length=13') }}"
  - set_fact:
    #application_name: keycloak
      postgres_name: postgres
      database_name: keycloak
      database_user: keycloak
      _apb_provision_creds:
        DB_PORT: "5432"
        DB_TYPE: postgres
        DB_HOST: postgresql
        DB_ADMIN_USER: postgres
        DB_ADMIN_PASSWORD: "{{ postgresql_admin_password }}"

        #  - ara_record:
        #      key: "hostvars"
        #      value: "{{ hostvars }}"
        #      type: "dict"
        #  - ara_record:
        #      key: "vars"
        #      value: "{{ vars }}"
        #      type: "dict"

  - include_role:
      name: postgresql-apb/rhscl-postgresql-apb
  - include_role:
      name: postgresql-apb/bind-rhscl-postgresql-apb
    vars:
      postgresql_db_name: "{{ database_name }}"
      postgresql_user: "{{ database_user }}"
      postgresql_password: "{{ gen_password }}"
      postgresql_superuser: false
      encode: False
  - include_role:
      name: postgresql-apb/bind-rhscl-postgresql-apb
    vars:
      postgresql_db_name: "dbche"
      postgresql_user: "pgche"
      postgresql_password: "pgchepassword"
      postgresql_superuser: true
      encode: False

  - name: Create Postgres secret
    k8s_v1_secret:
      name: '{{ postgres_name }}'
      namespace: '{{ namespace }}'
      labels:
        app: rhscl-postgresql-apb
      annotations:
        template.openshift.io/expose-username: "{.data['database-user']}"
        template.openshift.io/expose-password: "{.data['database-password']}"
        template.openshift.io/expose-database_name: "{.data['database-name']}"
      string_data:
        database-user: '{{ database_user }}'
        database-password: '{{ gen_password }}'
        database-name: '{{ database_name  | replace("-", "_") }}'

  - name: Create Postgres service
    k8s_v1_service:
      name: '{{ postgres_name }}'
      namespace: '{{ namespace }}'
      labels:
        app: rhscl-postgresql-apb
      annotations:
        template.openshift.io/expose-uri: postgres://{.spec.clusterIP}:{.spec.ports[?(.name=="postgresql")].port}
      ports:
      - name: postgresql
        protocol: TCP
        port: 5432
        target_port: 5432
        node_port: 0
      selector:
        app: rhscl-postgresql-apb
        service: postgresql-9.6-prod
      spec_type: ClusterIP
      session_affinity: None

  - name: "Create temporary keycloak directory"
    file:
      path: /tmp/keycloak
      state: directory

  - include_role:
      name: keycloak-apb/provision-keycloak-apb
      tasks_from: deploy-keycloak.yml
    vars:
      application_name: keycloak
      admin_username: admin
      admin_password: admin

  - include_role:
      name: keycloak-apb/set-keycloak-uri
    vars:
      application_name: keycloak
      admin_username: admin
      admin_password: admin

  - name: delete keycloak https route
    openshift_v1_route:
      name: 'keycloak'
      namespace: '{{ namespace }}'
      state: 'absent'

  - name: Create keycloak http route
    openshift_v1_route:
      name: 'keycloak'
      namespace: '{{ namespace }}'
      labels:
        app: 'keycloak'
        service: 'keycloak'
      to_name: 'keycloak'
      to_kind: 'Service'
      spec_port_target_port: 'web'
    register: keycloak_route_raw

  - name: Set keycloak uri from route
    set_fact:
      keycloak_uri: 'http://{{ keycloak_route_raw.route.spec.host }}'

  - ara_record:
      key: "hostvars"
      value: "{{ hostvars }}"
      type: "dict"
  - ara_record:
      key: "vars"
      value: "{{ vars }}"
      type: "dict"


  - include_role:
      name: provision-eclipse-che-apb
    vars:
      keycloak_admin_username: admin
      keycloak_admin_password: admin

